Repository ZZIPSA/kkuk-kkuk-fe, pull requests merged in 2024-05, with the labels that each got.

#17 #8 전체 Kit 조회 페이지 `/kits` 뷰 완성
  app/kits/components.tsx
  app/kits/components/KitCard.tsx
  app/kits/page.tsx
  app/layout.tsx
  stories/Tag.tsx
  tailwind.config.ts
Labels: feature

#19 #12 랠리 카테고리 API 구현
  .gitignore
  app/api/rallies/[id]/route.ts
  app/api/rallies/route.ts
  lib/prisma/db.ts
  lib/prisma/index.ts
  lib/prisma/selects.ts
  next.config.mjs
  package.json
  prisma/migrations/20240515161925_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  types/dummy.ts
  types/kit.ts
  types/rally.ts
  types/requests/rallyRequest.ts
  types/responses/rallyResponses.ts
  types/user.ts
  yarn.lock
Labels: feature

#34 issue/#22 Get Kits, Get Kit, Get User, Get My Rallies API 추가
  app/api/kits/[id]/route.ts
  app/api/kits/route.ts
  app/api/my/[id]/route.ts
  app/api/rallies/route.ts
Labels: feature

#31 #27 빌드 과정 시 오류 해결
  app/kits/components/KitCard.tsx
  app/kits/new/components/NewKitForm/Stamps.tsx
  app/kits/new/components/NewKitForm/schema.ts
  app/kits/page.tsx
  app/kits/types.ts
  lib/notFound.ts
  lib/prisma/index.ts
  lib/prisma/selects.ts
  src/components/ui/AlertDialog.tsx
  stories/Button.stories.ts
  stories/Header.stories.ts
  stories/Header.tsx
  stories/Page.stories.ts
  stories/Page.tsx
  stories/header.css
  stories/page.css
  types/kit.ts
Labels: bug

#32 헤더 완성
  app/components/NavBar.tsx
  app/layout.tsx
  app/lib.tsx
  app/types.ts
  lib/constants.ts
  lib/icons.tsx
  next.config.mjs
  package.json
  public/default-profile.svg
  public/pencil.svg
  public/stamp.svg
  yarn.lock
Labels: feature

#46 issue/#20 refactor: 타입 정리
  app/components/NavBar.tsx
  app/kits/components/KitCard.tsx
  app/kits/page.tsx
  app/lib.tsx
  prisma/schema.prisma
  types/Rally.ts
  types/kit.ts
  types/models.ts
Labels: refactoring

#52 Issue/#40 특정 키트 조회 페이지 완성
  app/api/kits/[id]/route.ts
  app/kits/[id]/components/RallyPreview/Stamp.tsx
  app/kits/[id]/components/RallyPreview/index.tsx
  app/kits/[id]/components/StampsPreview/index.tsx
  app/kits/[id]/page.tsx
  app/kits/[id]/start/page.tsx
  app/kits/[kitId]/page.tsx
  app/kits/components/KitCard.tsx
  app/kits/page.tsx
  assets/bookmark.svg
  assets/check.svg
  assets/heart.svg
  assets/pencil.svg
  assets/stamp.svg
  assets/trash.svg
  components/KitCard/index.tsx
  lib/constants.ts
  lib/icons.tsx
  public/rally-route.svg
  tailwind.config.ts
  types/Stamp.ts
Labels: feature

#59 키트 생성 API 구현
  app/api/kits/[id]/route.ts
  app/api/kits/route.ts
  app/api/my/route.ts
  app/api/rallies/[id]/route.ts
  app/api/s3/presign/route.ts
  app/upload/page.tsx
  next.config.mjs
  package.json
  prisma/migrations/20240521223732_init/migration.sql
  prisma/migrations/20240522064053_make_kit_id_to_padded/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  yarn.lock
Labels: feature

#72 #14 트위터 로그인 구현
  app/api/auth/[...nextauth]/route.ts
  app/api/kits/route.ts
  app/api/my/route.ts
  app/auth/signin/page.tsx
  auth.ts
  package.json
  prisma/migrations/20240523093848_set_email_as_optional/migration.sql
  prisma/migrations/20240523121703_hotfix_set_auth_schema/migration.sql
  prisma/migrations/20240523123915_change_schema_name/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  yarn.lock
Labels: feature

#71 #47 태그가 두 줄이 되는 현상 해결
  stories/Tag.tsx
Labels: feature

#69 #68 랠리 시작 페이지 레이아웃 완성
  app/api/kits/[id]/route.ts
  app/components/NavBar/index.tsx
  app/components/NavBar/lib.tsx
  app/components/NavBar/types.ts
  app/globals.css
  app/kits/[id]/page.tsx
  app/kits/[id]/start/components/RallyStartForm/DescriptionField.tsx
  app/kits/[id]/start/components/RallyStartForm/TitleField.tsx
  app/kits/[id]/start/components/RallyStartForm/index.tsx
  app/kits/[id]/start/components/RallyStartForm/schema.ts
  app/kits/[id]/start/page.tsx
  app/rallies/page.tsx
  components/KitCard/index.tsx
  components/ui/form.tsx
  prisma/seed-user-rally.ts
  tailwind.config.ts
  types/Kit.ts
Labels: feature

#85 #77 에러 페이지 완성
  app/components/ErrorContent.tsx
  app/components/styles.ts
  app/error-page-for-dev/page.tsx
  app/error.tsx
  app/global-error.tsx
  assets/error-icon.svg
  lib/constants.ts
  lib/icons.tsx
  tailwind.config.ts
Labels: feature

#79 이미지 블러 기능 구현 및 이미지 업로드 API 리팩토링
  app/api/kits/assets/actions.ts
  app/api/kits/route.ts
  app/api/s3/presign/route.ts
  app/upload/page.tsx
  lib/constants.ts
  lib/services/s3.ts
  lib/sharp.ts
  package.json
  prisma/migrations/20240526125044_add_blurred_image/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  yarn.lock
Labels: refactoring
