Repository ZZIPSA/kkuk-kkuk-fe, pull requests merged in 2024-06, with the labels that each got.

#83 #82 키트 생성 페이지 스탬프 이미지 업로드 섹션 레이아웃 완성
  app/kits/new/components/NewKitForm/Description.tsx
  app/kits/new/components/NewKitForm/Stamps.tsx
  app/kits/new/components/NewKitForm/Stamps/EmptyStamp.tsx
  app/kits/new/components/NewKitForm/Stamps/StampInput.tsx
  app/kits/new/components/NewKitForm/Stamps/StampPreview.tsx
  app/kits/new/components/NewKitForm/Stamps/index.tsx
  app/kits/new/components/NewKitForm/Stamps/lib.ts
  app/kits/new/components/NewKitForm/Stamps/styles.ts
  app/kits/new/components/NewKitForm/Tags.tsx
  app/kits/new/components/NewKitForm/Title.tsx
  app/kits/new/components/NewKitForm/constants.ts
  app/kits/new/components/NewKitForm/index.tsx
  app/kits/new/components/NewKitForm/schema.ts
  app/kits/new/components/NewKitForm/types.ts
  app/kits/new/page.tsx
  assets/circle-plus.svg
  assets/gift.svg
  assets/picture.svg
  components/ui/input.tsx
  lib/icons.tsx
  stories/Input.stories.ts
  stories/Input.tsx
Labels: feature

#89 API 완성 및 마무리
  app/api/kits/[id]/route.ts
  app/api/kits/assets/actions.ts
  app/api/kits/route.ts
  app/api/me/route.ts
  app/api/my/kits/route.ts
  app/api/my/rallies/route.ts
  app/api/rallies/[id]/route.ts
  app/api/rallies/route.ts
  app/api/s3/presign/route.ts
  app/api/user/[id]/kits/route.ts
  app/api/user/[id]/rallies/route.ts
  app/api/user/[id]/route.ts
  auth.ts
  lib/constants.ts
  lib/prisma/selects.ts
  lib/services/s3.ts
Labels: feature

#96 #91 모든 페이지 너비 일괄 고정
  app/components/NavBar/index.tsx
  app/globals.css
  app/kits/[id]/start/components/RallyStartForm/TitleField.tsx
  app/kits/new/page.tsx
  app/kits/page.tsx
  app/layout.tsx
  app/rallies/page.tsx
  components/UserInfo/NicknameInput.tsx
  components/ui/navigation-menu.tsx
Labels: bug

#95 #70 랠리 페이지 레이아웃 완성
  app/kits/[id]/components/RallyPreview/Stamp.tsx
  app/kits/[id]/components/RallyPreview/index.tsx
  app/rallies/[id]/components/RallyFooter.tsx
  app/rallies/[id]/components/RallyInfo.tsx
  app/rallies/[id]/components/RallyStamps.tsx
  app/rallies/[id]/components/lib.ts
  app/rallies/[id]/components/styles.ts
  app/rallies/[id]/components/types.ts
  app/rallies/[id]/lib.ts
  app/rallies/[id]/page.tsx
  components/RallyStamp/index.tsx
  components/RallyStamp/lib.ts
  components/RallyStamp/styles.ts
  components/RallyStamp/types.ts
  components/ui/progress.tsx
  lib/constants.ts
  lib/date.ts
  package.json
  public/rally-flag.svg
  tailwind.config.ts
  types/Rally.ts
  yarn.lock
Labels: feature

#107 issue/#105 feat: auth관련 API 수정
  app/api/kits/assets/actions.ts
  app/api/kits/route.ts
  app/api/me/route.ts
  app/api/my/rallies/route.ts
  app/api/rallies/route.ts
  app/my/(info)/completes/page.tsx
  app/my/(info)/joins/page.tsx
  components/UserInfo/index.tsx
Labels: bug

#108 #106 랠리 시작 페이지 레이아웃 깨짐 해결
  app/kits/[id]/page.tsx
  app/kits/[id]/start/page.tsx
  components/KitCard/KitCardContent.tsx
  components/KitCard/KitCardFooter.tsx
  components/KitCard/KitCardHeader.tsx
  components/KitCard/index.tsx
  components/KitCard/lib.ts
  components/KitCard/styles.ts
  components/KitCard/types.ts
  stories/Tag.tsx
Labels: bug

#111 #110 유저 정보 수정 페이지 레이아웃 MVP 변경 적용
  app/my/settings/components/TeamInfo/index.tsx
  app/my/settings/components/UserSettings/index.tsx
  app/my/settings/page.tsx
  assets/team-logo.svg
  auth.ts
  components/UserInfo/NicknameInput.tsx
  components/UserInfo/ProfileImage.tsx
  components/UserInfo/index.tsx
  components/ui/avatar.tsx
  lib/constants.ts
  lib/icons.tsx
Labels: feature

#109 #104 마이 페이지 비어있을 경우
  app/my/(info)/completes/page.tsx
  app/my/(info)/components/EmptyContent/index.tsx
  app/my/(info)/joins/page.tsx
  app/my/(info)/layout.tsx
  app/my/(info)/uploads/page.tsx
Labels: feature

#98 #97 완료된 랠리 페이지 레이아웃 및 #100 랠리 비소유자가 보는 페이지 레이아웃 완성
  app/rallies/[id]/components/RallyFooter.tsx
  app/rallies/[id]/components/RallyStamps.tsx
  app/rallies/[id]/components/lib.ts
  app/rallies/[id]/components/styles.ts
  app/rallies/[id]/components/types.ts
  app/rallies/[id]/lib.ts
  app/rallies/[id]/page.tsx
  app/rallies/page.tsx
Labels: feature

#124 #123 #113 머지 이후 빌드 시 발생하는 에러 해결
  app/error-page-for-dev/page.tsx
  prisma/seed-user-rally.ts
  stories/Input.stories.ts
  types/Kit.ts
Labels: bug

#129 #128 브라우저 콘솔에서 발생하는 오류 제거
  app/api/my/rallies/route.ts
  app/api/s3/presign/route.ts
  app/kits/[id]/components/StampsPreview/index.tsx
  app/kits/new/components/NewKitForm/Stamps/StampPreview.tsx
  app/kits/new/components/NewKitForm/Stamps/index.tsx
  app/my/(info)/joins/page.tsx
  app/rallies/[id]/lib.ts
  app/rallies/[id]/page.tsx
  app/rallies/page.tsx
  components/KitCard/KitCardHeader.tsx
  components/RallyCard/index.tsx
  components/RallyStamp/index.tsx
  components/ui/form.tsx
  package.json
  prisma/seed-user-rally.ts
  types/Kit.ts
  types/Rally.ts
Labels: bug

#122 #121 키트 생성 모달 레이아웃 완성
  app/kits/new/components/NewKitForm/SuccessModal.tsx
  app/kits/new/components/NewKitForm/index.tsx
  app/layout.tsx
  assets/paw.svg
  components/Modal/index.tsx
  components/Modal/lib.ts
  components/ui/sonner.tsx
  lib/constants.ts
  lib/icons.tsx
  lib/utils.ts
  package.json
  yarn.lock
Labels: feature

#140 #136 #137 #138 #139 해결
  app/globals.css
  app/kits/[id]/components/RallyPreview/index.tsx
  app/kits/[id]/components/StampsPreview/index.tsx
  app/kits/[id]/start/components/RallyStartForm/DescriptionField.tsx
  app/kits/[id]/start/components/RallyStartForm/Submit.tsx
  app/kits/[id]/start/components/RallyStartForm/TitleField.tsx
  app/kits/[id]/start/components/RallyStartForm/index.tsx
  app/kits/[id]/start/components/RallyStartForm/types.ts
  app/kits/new/components/NewKitForm/Submit.tsx
  app/kits/new/components/NewKitForm/index.tsx
  app/my/(info)/components/MenuTabs/MenuTab.tsx
  app/my/(info)/components/MenuTabs/index.tsx
  app/my/settings/@modal/(.)delete-account/page.tsx
  app/rallies/[id]/components/RallyStamps.tsx
  app/rallies/[id]/components/lib.ts
  app/rallies/[id]/components/styles.ts
  assets/pencil-plus.svg
  components/RallyStamp/index.tsx
  components/Submit/index.tsx
  lib/icons.tsx
Labels: bug

#130 #43 키트 생성 태그 입력 필드
  app/kits/new/components/NewKitForm/Tags.tsx
  app/kits/new/components/NewKitForm/index.tsx
  app/kits/new/components/NewKitForm/lib.ts
  app/kits/new/components/NewKitForm/schema.ts
  app/kits/new/components/NewKitForm/styles.ts
  app/kits/new/components/NewKitForm/types.ts
  app/kits/new/page.tsx
  lib/constants.ts
Labels: feature

#132 #131 키트 생성 페이지 스탬프 이미지 업로드 섹션 로직 완성
  app/kits/new/components/NewKitForm/Stamps/StampInput.tsx
  app/kits/new/components/NewKitForm/Stamps/StampPreview.tsx
  app/kits/new/components/NewKitForm/Stamps/actions.ts
  app/kits/new/components/NewKitForm/Stamps/index.tsx
  app/kits/new/components/NewKitForm/Stamps/lib.ts
  app/kits/new/components/NewKitForm/Stamps/styles.ts
  app/kits/new/components/NewKitForm/index.tsx
  app/kits/new/components/NewKitForm/schema.ts
  app/kits/new/components/NewKitForm/types.ts
  assets/trash.svg
  components/ui/loading.tsx
  lib/constants.ts
Labels: feature

#152 #150 storybook 제거
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  app/rallies/[id]/components/RallyFooter.tsx
  components/KitCard/KitCardContent.tsx
  components/NavBar/lib.tsx
  components/Submit/index.tsx
  components/Tag/index.tsx
  components/UserInfo/NicknameInput.tsx
  components/ui/button.tsx
  package.json
  stories/Button.stories.ts
  stories/Button.tsx
  stories/Configure.mdx
  stories/Input.stories.ts
  stories/Input.tsx
  stories/Tag.stories.ts
  stories/assets/accessibility.png
  stories/assets/accessibility.svg
  stories/assets/addon-library.png
  stories/assets/assets.png
  stories/assets/avif-test-image.avif
  stories/assets/context.png
  stories/assets/discord.svg
  stories/assets/docs.png
  stories/assets/figma-plugin.png
  stories/assets/github.svg
  stories/assets/share.png
  stories/assets/styling.png
  stories/assets/testing.png
  stories/assets/theming.png
  stories/assets/tutorials.svg
  stories/assets/youtube.svg
  tailwind.config.ts
  yarn.lock
Labels: refactoring

#154 Issue/141 랠리 시작 / 스탬프 찍기 기능 구현
  app/api/lib/errors.ts
  app/api/lib/utils.ts
  app/api/rallies/[id]/route.ts
  app/api/rallies/route.ts
  app/kits/[id]/start/components/RallyStartForm/index.tsx
  app/kits/[id]/start/page.tsx
  app/rallies/[id]/components/RallyFooter.tsx
  app/rallies/[id]/page.tsx
  auth.ts
  next.config.mjs
Labels: feature

#162 #156 #160 #161 이슈 해결
  app/(back)/my/settings/@modal/(.)delete-account/Buttons.tsx
  app/(back)/my/settings/@modal/(.)delete-account/page.tsx
  app/(back)/rallies/[id]/components/styles.ts
  components/ui/button.tsx
Labels: bug
